#! /bin/sh
. $HOME/.colors.sh

bspc rule -a TelegramDesktop:Telegram desktop=^3 split_dir="west"
bspc rule -a xterm-256color:mutt desktop=^3 split_dir="north"
bspc rule -a xterm-256color:weechat desktop=^3 split_dir="south"
bspc rule -a qutebrowser desktop=^2 split_ratio="0.7"
bspc rule -a Zathura:zathura state=tiled

# restarting dunst and polybar, resetting wallpaper and layout
feh --bg-scale $HOME/.wp.jpg
polybar-msg cmd restart
$HOME/.config/dunst/wrapper.sh &
setxkbmap de,ru -option caps:escape -option grp:shifts_toggle
xset r rate 280 35

bspc monitor -d msc web cht uni wrk mus cnf

bspc config border_width         	3
bspc config window_gap           	0

bspc config split_ratio          	0.5
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config remove_disabled_monitors	true
bspc config remove_unplugged_monitors	true
bspc config normal_border_color		"$background"
bspc config active_border_color		"$background"
bspc config focused_border_color	"$bgeven"
bspc config presel_feedback_color	"$darkgrey"
bspc config focus_follows_pointer true

bspc config external_rules_command ~/.config/bspwm/scripts/autopresel
